42-webserver/webserv

Makefile
README.md
srcs/main.cpp

Create README.md, Makefile, main.cpp

Initial webserv

---

.gitignore
webserv.mdj

starUML diagram file upload

---

README.md

Modify README: Index

---

Makefile
README.md
assets/webserv.mdj
incs/Server/Server.hpp
incs/config/Config.hpp
incs/err/err.hpp
incs/server/Server.hpp
srcs/config/Config.cpp
srcs/main.cpp

- config.hpp, config.cpp, server.hpp, server.cpp, err.hpp 작성했습니다.
- 
-

[feat] config, server 작성 #8

---

srcs/http/parser/HttpParser.hpp
srcs/http/request/HttpRequest.hpp
srcs/http/response/HttpResponse.hpp

- http class, http parser 추가
-
-

[Feat] add http classes #10

---

Makefile
config/webserv.conf
incs/config/Config.hpp
incs/server/Server.hpp
srcs/config/Config.cpp
srcs/main.cpp
srcs/server/Server.cpp

- refactoring: add constness to objects
-
-

[fix] refactoring #13

---

incs/kqueue/Kqueue.hpp
incs/server/Server.hpp
incs/socket/Socket.hpp
srcs/kqueue/Kqueue.cpp
srcs/main.cpp
srcs/server/Server.cpp
srcs/socket/Socket.cpp

- I/O Multiplexing
> 1. [o]  kqueue initialize
> 2. [o] kqueue setEvent
> 3. [o] kqueue getEventCount
> 4. [o] socket bind
> 5. [o] socket listen
> 6. [o] socket accept
> 7. [o] server initialize
-

Feat/IO Multiplexing#27

---

srcs/http/handler/HttpRequestHandler.cpp
srcs/http/parser/HttpParser.cpp
srcs/http/test/ResponseTest.cpp

- response stringstream으로 만들도록 수정
-
-

[Fix] response stringstream으로 만들도록 수정 #21

---

config/temp.conf
config/webserv.conf
incs/kqueue/Kqueue.hpp
incs/server/Server.hpp
incs/socket/Socket.hpp
srcs/config/Config.cpp
srcs/kqueue/Kqueue.cpp
srcs/server/Server.cpp
srcs/socket/Socket.cpp

- Debug, refactoring
- Feature non-blocking I/O multiplexing
-
-

Feat/non blocking#31

---

Makefile
libs/shared_ptr/incs/shared_ptr.hpp

Feat/shared ptr#35

---

Makefile
incs/http/request/HttpRequest.hpp
srcs/http/parser/HttpRequestParser.cpp
srcs/http/request/HttpRequest.cpp

HttpRequest fix

---

Makefile
incs/http/parser/HttpRequestParser.hpp
srcs/http/parser/HttpRequestParser.cpp
srcs/http/test/ParseReqeustTest.cpp

[Fix] http request parser 수정

---

Makefile
config/webserv.conf
incs/config/Config.hpp
incs/server/Location.hpp
incs/server/Server.hpp
srcs/config/Config.cpp
srcs/server/Location.cpp
srcs/server/Server.cpp
srcs/server/Webserv.cpp

- Location config implemented
-
-

Feat/more config settings#47

---

incs/http/parser/HttpRequestParser.hpp
incs/http/request/HttpRequest.hpp
srcs/http/parser/HttpRequestParser.cpp
srcs/http/request/HttpRequest.cpp

[Fix] request parser 수정 #49

---

Makefile
incs/Server/Server.hpp
incs/VirtualServerMap/VirtualServerMap.hpp
srcs/Server/Server.cpp
srcs/VirtualServerMap/Test/thisTest.cpp
srcs/VirtualServerMap/VirtualServerMap.cpp

feat:virtualServerMap.cpp

---

Makefile
incs/Event/Event.hpp
incs/Event/ListenEvent.hpp
incs/Event/ReadEvent.hpp
incs/EventDto/EventDto.hpp
incs/FileDescriptor/FileDescriptor.hpp
incs/VirtualServerMap/VirtualServerMap.hpp
srcs/Event/Event.cpp
srcs/Event/ListenEvent.cpp
srcs/Event/ReadEvent.cpp
srcs/Event/test/ListenEvTest.cpp
srcs/EventDto/EventDto.cpp
srcs/FileDescriptor/FileDescriptor.cpp
srcs/FileDescriptor/Test/filetest.cpp
srcs/VirtualServerMap/Test/thisTest.cpp
srcs/VirtualServerMap/VirtualServerMap.cpp

Fix/abstract factory#71

---

incs/http/parser/HttpRequestParser.hpp
incs/http/request/HttpRequest.hpp
srcs/http/parser/HttpRequestParser.cpp
srcs/http/request/HttpRequest.cpp

FIX http psrser

---

incs/http/parser/HttpRequestParser.hpp
srcs/http/parser/HttpRequestParser.cpp

- http parser compile되도록 수정
-
-

FIX http parser compile

---

incs/Event/Event.hpp
incs/Event/ReadEvent.hpp
incs/EventDto/EventDto.hpp
incs/EventQueue/EventQueue.hpp
incs/FileDescriptor/FileDescriptor.hpp
incs/Log/logger.hpp
incs/http/parser/HttpRequestParser.hpp
srcs/Config/Config.cpp
srcs/Event/BufReadHandler.cpp
srcs/Event/ListenEvent.cpp
srcs/Event/ReadEvent.cpp
srcs/EventQueue/EventQueue.cpp
srcs/FileDescriptor/FileDescriptor.cpp
srcs/Server/VirtualServer.cpp
srcs/Server/Webserv.cpp
srcs/Socket/Socket.cpp
srcs/http/parser/HttpRequestParser.cpp

fix:Refactoring-Comments#92

---

incs/Config/Config.hpp
srcs/Config/Config.cpp
srcs/main.cpp

- Config constructor 구현 startParse method로 추출
-
-

[fix] Config constructor to startParse method-93

---

incs/http/request/HttpRequest.hpp
srcs/http/request/HttpRequest.cpp

- httprequest에 getHost 추가 
-
-

[fix] httpRequest

---

Makefile
incs/Config/Config.hpp
incs/Server/PhysicalServerManager.hpp
incs/Server/VirtualServer.hpp
incs/Server/VirtualServerManager.hpp
incs/Server/Webserv.hpp
libs/Trie/test.hpp
libs/trie/TestTrie.cpp
srcs/Server/PhysicalServerManager.cpp
srcs/Server/Test/testVirtualServerManager.cpp
srcs/Server/VirtualServer.cpp
srcs/Server/VirtualServerManager.cpp
srcs/Server/Webserv.cpp
srcs/main.cpp

-
2. seperate Method
3. No Many Test
-
-

99 fix for servers

---

incs/Server/PhysicalServer.hpp
incs/Server/PhysicalServerManager.hpp
incs/Server/VirtualServerManager.hpp
srcs/Server/PhysicalServer.cpp
srcs/Server/PhysicalServerManager.cpp
srcs/Server/VirtualServerManager.cpp

- Implement findServer function
-
-

[Feat] findServer #113

---

srcs/Server/VirtualServerManager.cpp

Implement findVirtualServer by wildcard
-
-
-

[Fix] findVirtualServer #117

---

LogSave/Log.txt
incs/Server/Location.hpp
incs/Server/VirtualServer.hpp
libs/Trie/Trie.hpp
libs/shared_ptr/shared_ptr.hpp
srcs/Server/Location.cpp
srcs/Server/VirtualServer.cpp
srcs/Server/VirtualServerManager.cpp
srcs/route/RouteOrAliasHandler.cpp

Location vector to Location Trie
-
-
-

[Fix] Location #113

---

libs/shared_ptr/shared_ptr.hpp

- Implement make_shared, pointer_cast
-
-

[Feat] shared_ptr #128

---

Makefile
incs/Config/LocationElement.hpp
incs/Http/Parser/ChunkedRequestBodyHandler.hpp
incs/Http/Parser/HttpRequestParser.hpp
incs/Http/Parser/MultipartRequestBodyHandler.hpp
incs/Http/Parser/NormalBodyHandler.hpp
incs/Http/Parser/RequestBodyHandler.hpp
incs/Http/Utils/RouterUtils.hpp
srcs/Config/LocationElement.cpp
srcs/Http/Parser/ChunkedRequestBodyHandler.cpp
srcs/Http/Parser/HttpRequestParser.cpp
srcs/Http/Parser/MultipartRequestBodyHandler.cpp
srcs/Http/Parser/NormalBodyHandler.cpp
srcs/Http/Parser/RequestBodyHandler.cpp
srcs/Http/Utils/RouterUtils.cpp

135 feat chunk file upload

---

Makefile
config/webserv.conf
incs/Config/AllowMethodElement.hpp
incs/Config/ConfigElement.hpp
incs/Config/ConfigElementFactory.hpp
incs/Config/LocationElement.hpp
incs/Server/VirtualServerManager.hpp
srcs/Config/AllowMethodElement.cpp
srcs/Config/Config.cpp
srcs/Config/ConfigElement.cpp
srcs/Config/ConfigElementFactory.cpp
srcs/Config/LocationElement.cpp
srcs/Config/LocationTrieElement.cpp
srcs/Config/ServerElement.cpp
srcs/Server/Webserv.cpp

[Feat] allow_method #143

---

incs/Cache/LruCache.hpp
incs/Cache/cache.hpp
srcs/Cache/LruCache.cpp
srcs/Cache/cache.cpp

-
-fix Cache SingleTon
- Cache in LruCache
-

fix Cache SingleTon

---

Makefile
incs/Cache/LruCache.hpp
srcs/Cache/LruCache.cpp
srcs/Cache/cache.cpp

fix cache#152

---

incs/Http/Request/HttpRequest.hpp
incs/Http/Response/HttpResponse.hpp
srcs/Http/Request/HttpRequest.cpp
srcs/Http/Response/HttpResponse.cpp

- stream override
- HttpRequest, HttpResponse
-

[feat] stream override # 156

---

incs/Http/Parser/HttpRequestParser.hpp
incs/Http/Request/HttpRequest.hpp
incs/Http/Response/HttpResponse.hpp
incs/Http/Utils/Cookie.hpp
srcs/Http/Parser/HttpRequestParser.cpp
srcs/Http/Request/HttpRequest.cpp
srcs/Http/Response/HttpResponse.cpp

fix stream

---

Makefile
incs/Http/Parser/ChunkedRequestBodyHandler.hpp
incs/Http/Parser/HttpRequestParser.hpp
incs/Http/Parser/MultipartRequestBodyHandler.hpp
incs/Http/Parser/NormalBodyHandler.hpp
incs/Http/Parser/ParsePatternMatcher.hpp
incs/Http/Parser/RequestBodyHandler.hpp
incs/Http/Request/HttpRequest.hpp
incs/Http/Request/MultipartRequest.hpp
srcs/Http/Parser/ChunkedRequestBodyHandler.cpp
srcs/Http/Parser/HttpRequestParser.cpp
srcs/Http/Parser/MultipartRequestBodyHandler.cpp
srcs/Http/Parser/NormalBodyHandler.cpp
srcs/Http/Request/HttpRequest.cpp
srcs/Http/Request/MultipartRequest.cpp
srcs/Http/Test/MultipartRequestBodyTest.cpp

162 fix parser

---

incs/Http/Utils/FileUploader.hpp
incs/Http/Utils/RouterUtils.hpp
srcs/Http/Utils/FileUploader.cpp
srcs/Http/Utils/RouterUtils.cpp

164 fix router utils

---

srcs/Buffer/Node/BaseNode.cpp

[fix] buffer end(node end) #175

---

LogSave/Log.txt
Makefile
config/webserv.conf
incs/Config/CgiPassElement.hpp
incs/Config/LocationElement.hpp
srcs/Config/CgiPassElement.cpp
srcs/Config/ConfigElementFactory.cpp
srcs/Config/LocationElement.cpp
srcs/Server/Webserv.cpp
srcs/main.cpp

[Feat] cgi_pass element 구현 #180

---

incs/Http/Parser/HttpRequestParser.hpp
incs/Http/Request/HttpRequest.hpp
incs/Http/Request/MultipartRequest.hpp
srcs/Event/ReadEvent/ReadEventFromClientHandler.cpp
srcs/Http/Parser/HttpRequestParser.cpp
srcs/Http/Parser/MultipartRequestBodyHandler.cpp
srcs/Http/Request/HttpRequest.cpp
srcs/Http/Request/MultipartRequest.cpp

- fix request parser http request
- request parser 로직 수정
- HttpRequest 객체 body 타입 수정
- MultipartRequest 객체 body 타입 수정
-

182 fix request parser http request

---

incs/Http/Client.hpp
incs/Http/Utils/RouterUtils.hpp
srcs/Http/Client.cpp
srcs/Http/Utils/RouterUtils.cpp

- client class에서 cgi request인지 확인하는 추가로직 구현
-
-

[fix] client class return cgi read #184

---

Makefile
incs/Cache/LruCache.hpp
incs/Cache/cache.hpp
incs/Http/Client.hpp
incs/Pattern/CgiReaderProcessor.hpp
incs/Pattern/FileDeleterProcessor.hpp
incs/Pattern/FileReaderProcessor.hpp
incs/Pattern/FileWriterProcessor.hpp
incs/Pattern/PatternProcessor.hpp
incs/Pattern/ProcessorObject.hpp
srcs/Cache/LruCache.cpp
srcs/Cache/cache.cpp
srcs/Http/Client.cpp
srcs/Pattern/CgiReaderProcessor.cpp
srcs/Pattern/FileDeleterProcessor.cpp
srcs/Pattern/FileReaderProcessor.cpp
srcs/Pattern/FileWriterProcessor.cpp
srcs/Pattern/PatternProcessor.cpp
srcs/Pattern/ProcessorObject.cpp

-
-pattern Processor Interface
-fix location Pattern Type
- add File Writer Processor
- add File Reader Processor
- add cgi Reader Processor
- add File Deleter Processor
-

[feat] PatternProcessor Interface#189

---

incs/Http/Client.hpp
srcs/Http/Client.cpp

[fix] client class

---

incs/Http/Utils/RouterUtils.hpp
incs/Pattern/PatternProcessor.hpp
srcs/Client/Client.cpp
srcs/Http/Utils/RouterUtils.cpp

- client class add return enum
-
-

[fix] client class add return enum #200

---

incs/Config/AllowMethodElement.hpp
srcs/Config/AllowMethodElement.cpp

[Fix] AllowMethod Element PUT method 추가 #203

---

Makefile
incs/Hash/sha256.h
srcs/Hash/DirectoryListing.cpp
srcs/Hash/Etag.cpp
srcs/Hash/Sha256_copy.cpp

-directory Listing, generateEtag
- sha256(source Copy)를 통한 Etag구현
- directory Listing (HTML) 구현

[feat] dirLisiting, generateEtag

---

incs/Http/Request/MultipartRequest.hpp
incs/Http/Utils/RouterUtils.hpp
srcs/Http/Request/MultipartRequest.cpp
srcs/Http/Utils/RouterUtils.cpp

- fix multipart, router
-  multipart request 함수 추가
- router auto index 기능 추가
- router allow method 기능 추가
-

202 fix router multipart

---

PathExample.txt
incs/Buffer/Buffer/IoReadAndWriteBuffer.hpp
incs/Buffer/Node/BaseNode.hpp
incs/Client/Client.hpp
incs/Client/ClientIdManager.hpp
incs/FileManager/FileState.hpp
incs/FileManager/FileTableManager/FileBufferManager.hpp
incs/FileManager/FileTableManager/FileIdent.hpp
incs/FileManager/FileTableManager/FileOperationController.hpp
srcs/Buffer/Buffer/IoReadAndWriteBuffer.cpp
srcs/Buffer/Node/BaseNode.cpp
srcs/Client/Client.cpp
srcs/Client/ClientIdManager.cpp
srcs/FileManager/FileTableManager/FileBufferManager.cpp
srcs/FileManager/FileTableManager/FileIdent.cpp
srcs/FileManager/FileTableManager/FileOperationController.cpp

-fix file buffermanager file operation controller
-fix file buffermanager file operation controller 
- 수정이 더 필요, 일단 프로세서 만들고 덜어낼거 덜어낼 예정

206 fix file buffermanager file operation controller

---

incs/FileManager/FileManager/FileManger.hpp
incs/FileManager/FileTableManager/FileTableManager.hpp
srcs/FileManager/Cache/LruCache.cpp
srcs/FileManager/FileManager/FileManager.cpp
srcs/FileManager/FileTableManager/FileTableManager.cpp

-215-feat-file-delete
-feat file delete

[feat] 215-feat-file-delete#215

---

incs/Client/Client.hpp
incs/Event/EventDto/EventDto.hpp
incs/Event/ReadEvent/ReadEventFromClient.hpp
incs/Event/ReadEvent/ReadEventFromClientHandler.hpp
incs/Event/WriteEvent/WriteEventToClient.hpp
srcs/Client/Client.cpp
srcs/Event/EventBase/EventFactory.cpp
srcs/Event/EventDto/EventDto.cpp
srcs/Event/ListenEvent/ListenEventHandler.cpp
srcs/Event/ReadEvent/ReadEventFromClient.cpp
srcs/Event/ReadEvent/ReadEventFromClientHandler.cpp
srcs/Event/WriteEvent/WriteEventToCacheHandler.cpp
srcs/Event/WriteEvent/WriteEventToClient.cpp

-fix ReadEventfromClient
-fix EventFactory
- fix WriteEventToClient member
- fix readeventClient logic

[fix] ReadEventFromClient

---

Makefile
incs/Buffer/Node/BaseNode.hpp
incs/Client/Client.hpp
incs/Event/ReadEvent/ReadEventFromClient.hpp
incs/Event/ReadEvent/ReadEventFromClientHandler.hpp
incs/Event/WriteEvent/WriteEventToClient.hpp
incs/Event/WriteEvent/WriteEventToClientHandler.hpp
incs/Pattern/CgiReaderProcessor.hpp
incs/Pattern/FileDeleterProcessor.hpp
incs/Pattern/FileWriterProcessor.hpp
incs/Pattern/PatternProcessor.hpp
incs/Pattern/PatternType.hpp
incs/Pattern/ProcessorObject.hpp
incs/Pattern/RedirectionProcessor.hpp
srcs/Buffer/Buffer/IoOnlyReadBuffer.cpp
srcs/Buffer/Node/BaseNode.cpp
srcs/Client/Client.cpp
srcs/Event/ReadEvent/ReadEventFromClient.cpp
srcs/Event/ReadEvent/ReadEventFromClientHandler.cpp
srcs/Event/WriteEvent/WriteEventToClient.cpp
srcs/Event/WriteEvent/WriteEventToClientHandler.cpp
srcs/Pattern/CgiReaderProcessor.cpp
srcs/Pattern/FileDeleterProcessor.cpp
srcs/Pattern/FileReaderProcessor.cpp
srcs/Pattern/FileWriterProcessor.cpp
srcs/Pattern/PatternProcessor.cpp
srcs/Pattern/RedirectionProcessor.cpp

- feat write Event handle
- error handling
- feat Write Event Handle

[fix] Write Event Flow

---

config/webserv.conf
incs/Buffer/Buffer/IoOnlyReadBuffer.hpp
incs/Cgi/CgiEnvSetter.hpp
incs/Channel/CgiChannel.hpp
incs/Channel/DualStreamable.hpp
incs/Channel/Socket.hpp
incs/Config/LocationTrieElement.hpp
incs/Event/ListenEvent/ListenEventHandler.hpp
incs/Http/Exception/InternalServerErrorException.hpp
incs/Http/Response/HttpResponse.hpp
incs/Http/Utils/RouterUtils.hpp
incs/Server/VirtualServerManager.hpp
libs/Trie/Trie.hpp
srcs/Cgi/CgiEnvSetter.cpp
srcs/Channel/CgiChannel.cpp
srcs/Channel/DualStreamable.cpp
srcs/Channel/Socket.cpp
srcs/Config/LocationTrieElement.cpp
srcs/Event/ListenEvent/ListenEvent.cpp
srcs/Event/ListenEvent/ListenEventHandler.cpp
srcs/Http/Response/HttpResponse.cpp
srcs/Http/Utils/RouterUtils.cpp
srcs/Server/VirtualServerManager.cpp

-226 fix trie And route
-226 fix trie And route

226 fix trie And route

---

Makefile
incs/Cgi/CgiEnvSetter.hpp
incs/Http/Utils/RouterUtils.hpp
srcs/Cgi/CgiEnvSetter.cpp
srcs/Http/Utils/RouterUtils.cpp

[feat] CgiEnvSetter

---

incs/Http/Utils/RouterUtils.hpp
srcs/Http/Utils/RouterUtils.cpp

- router utils add find redir uri function
-
-

[fix] router utils add find redir uri #225
